### ISSUE TITLE
Add support for Django 1.7

### ISSUE THREAD

**Issue by naegelyd** [chop-dbhi/serrano#274]

**Comment by sgithens** [comment]
@naegelyd Do you have an idea of what needs to change in order to support 1.7, 1.8, 1.9?  Do you think it's minor configuration and structure tweaks, or more major work that has to be done to accomodate API changes and other things in Django?

**Comment by naegelyd** [comment]
@sgithens Avocado had support Django 1.7 for a while now. https://github.com/chop-dbhi/serrano/pull/283 makes a couple very minor changes to add Django 1.7 support to Serrano. After https://github.com/chop-dbhi/serrano/pull/283, I believe Harvest could be considered to have Django 1.7 support. Django 1.8 will be a little trickier. I know some work will need to be done with migrations. Also, there are some deprecation warnings triggered on 1.7 that will need to be addressed as they are breaking changes in 1.8. I do not have a full list of things that would need to be addressed for Django 1.8 though the two items above are issues I know for sure will need to be handled. I would think that the work will be pretty minor but could involve updates to other libraries like we saw in the case of `django-preserialize`.

@bruth If Django 1.8 support was added, do you think we could drop support for Django 1.6(and with it, South style migrations) as it went out of extended support [in April 2015](https://www.djangoproject.com/download/). That might be a good `3.0` release for Avocado and Serrano.

**Comment by bruth** [comment]
Yes. I think it is time to transition to supporting the latest two versions only. If older versions manage to work then great, but they won't be supported otherwise.
