### ISSUE TITLE
Update serrano metadata on pypi

### ISSUE THREAD

**Issue by murphyke** [chop-dbhi/serrano#287]
Currently, there is a `serrano 2.4.0` entry, which gives a 404, and a `serrano 2.4.0.post1` entry.

**Comment by bruth** [comment]
When I originally uploaded the 2.4.0 release I noticed a problem with the packaging (not the code). I tried to upload a new package, but it denied it. The recommendation was to add `post1` suffix to the version. PyPi appeared to have added this constraint relatively recently. Bottom line is that there is no way I can upload the `2.4.0` version.
